name: Run Tests and Upload Coverage to Codecov

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov numpy

      # Set PYTHONPATH correctly for all OS
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: pytest --cov=src --cov=tests --cov-report=xml:coverage.xml --cov-report=term-missing -v

      # Verify that coverage.xml exists
      - name: Verify coverage.xml exists
        run: |
          if [ -f "./coverage.xml" ]; then echo "coverage.xml exists"; else echo "coverage.xml not found"; exit 1; fi
        shell: bash

      # List generated files to ensure the file is in the right place
      - name: List generated files
        run: ls -l
        shell: bash

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
